GMCC_CONTAINER_ITEMS = {
    { id = 38082, name = "\"Gigantique\" Bag", slots = 22, type = "Bag", family = "General", quality = 4, itemLevel = 70, requiredLevel = 0 },
    { id = 1977, name = "20-slot Bag", slots = 20, type = "Bag", family = "General", quality = 1, itemLevel = 1, requiredLevel = 0 },
    { id = 41597, name = "Abyssal Bag", slots = 32, type = "Soul Bag", family = "Soul Shards", quality = 3, itemLevel = 80, requiredLevel = 0 },
    { id = 4981, name = "Agmond's Belt Pouch", slots = 12, type = "Bag", family = "General", quality = 1, itemLevel = 35, requiredLevel = 0 },
    { id = 18714, name = "Ancient Sinew Wrapped Lamina", slots = 18, type = "Quiver", family = "Arrows", quality = 4, itemLevel = 75, requiredLevel = 60 },
    { id = 24270, name = "Bag of Jewels", slots = 24, type = "Gem Bag", family = "Gems", quality = 2, itemLevel = 65, requiredLevel = 0 },
    { id = 34490, name = "Bag of Many Hides", slots = 24, type = "Leatherworking Bag", family = "Leatherworking", quality = 3, itemLevel = 70, requiredLevel = 0 },
    { id = 3604, name = "Bandolier of the Night Watch", slots = 12, type = "Ammo Pouch", family = "Bullets", quality = 2, itemLevel = 25, requiredLevel = 0 },
    { id = 22249, name = "Big Bag of Enchantment", slots = 24, type = "Enchanting Bag", family = "Enchanting", quality = 2, itemLevel = 65, requiredLevel = 0 },
    { id = 5765, name = "Black Silk Pack", slots = 10, type = "Bag", family = "General", quality = 1, itemLevel = 25, requiredLevel = 0 },
    { id = 856, name = "Blue Leather Bag", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 14156, name = "Bottomless Bag", slots = 18, type = "Bag", family = "General", quality = 3, itemLevel = 62, requiredLevel = 0 },
    { id = 22244, name = "Box of Souls", slots = 16, type = "Soul Bag", family = "Soul Shards", quality = 2, itemLevel = 30, requiredLevel = 0 },
    { id = 4498, name = "Brown Leather Satchel", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 3343, name = "Captain Sanders' Booty Bag", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 22251, name = "Cenarion Herb Bag", slots = 20, type = "Herb Bag", family = "Herbs", quality = 2, itemLevel = 55, requiredLevel = 0 },
    { id = 29143, name = "Clefthoof Hide Quiver", slots = 18, type = "Quiver", family = "Arrows", quality = 3, itemLevel = 109, requiredLevel = 68 },
    { id = 21342, name = "Core Felcloth Bag", slots = 28, type = "Soul Bag", family = "Soul Shards", quality = 4, itemLevel = 60, requiredLevel = 0 },
    { id = 22571, name = "Courier's Bag", slots = 6, type = "Bag", family = "General", quality = 1, itemLevel = 1, requiredLevel = 0 },
    { id = 38307, name = "Crafty's Bottomless Inscription Bag", slots = 32, type = "Inscription Bag", family = "Inscription", quality = 4, itemLevel = 85, requiredLevel = 0 },
    { id = 19291, name = "Darkmoon Storage Box", slots = 14, type = "Bag", family = "General", quality = 1, itemLevel = 45, requiredLevel = 0 },
    { id = 38145, name = "Deathweave Bag", slots = 12, type = "Bag", family = "General", quality = 1, itemLevel = 35, requiredLevel = 0 },
    { id = 10959, name = "Demon Hide Sack", slots = 16, type = "Bag", family = "General", quality = 2, itemLevel = 55, requiredLevel = 0 },
    { id = 2003, name = "Deprecated Big Quiver", slots = 8, type = "Quiver", family = "Arrows", quality = 1, itemLevel = 1, requiredLevel = 1 },
    { id = 806, name = "Deprecated Brown Leather Satchel", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 4501, name = "Deprecated Brown Wayfarer's Knapsack", slots = 16, type = "Bag", family = "General", quality = 1, itemLevel = 55, requiredLevel = 0 },
    { id = 930, name = "Deprecated Deep Pocket Pouch", slots = 10, type = "Bag", family = "General", quality = 1, itemLevel = 25, requiredLevel = 0 },
    { id = 3298, name = "Deprecated Grizzled Bearskin Pouch", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 931, name = "Deprecated Heavy Brown Sack", slots = 10, type = "Bag", family = "General", quality = 1, itemLevel = 25, requiredLevel = 0 },
    { id = 2002, name = "Deprecated Jordan's Quiver", slots = 4, type = "Quiver", family = "Arrows", quality = 1, itemLevel = 1, requiredLevel = 1 },
    { id = 1724, name = "Deprecated Jungle Trail Pack", slots = 10, type = "Bag", family = "General", quality = 1, itemLevel = 25, requiredLevel = 0 },
    { id = 3568, name = "Deprecated Oslow's Toolbox", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 1281, name = "Deprecated Quiver (TEST)", slots = 4, type = "Quiver", family = "Arrows", quality = 1, itemLevel = 1, requiredLevel = 1 },
    { id = 965, name = "Deprecated Red Linen Sack", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 184, name = "Deprecated Small Brown Pouch", slots = 6, type = "Bag", family = "General", quality = 1, itemLevel = 5, requiredLevel = 0 },
    { id = 2115, name = "Deprecated Small White Pouch", slots = 6, type = "Bag", family = "General", quality = 1, itemLevel = 5, requiredLevel = 0 },
    { id = 855, name = "Deprecated White Leather Satchel", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 13330, name = "Dereks Radish Bag", slots = 18, type = "Bag", family = "General", quality = 1, itemLevel = 1, requiredLevel = 1 },
    { id = 918, name = "Deviate Hide Pack", slots = 10, type = "Bag", family = "General", quality = 1, itemLevel = 25, requiredLevel = 0 },
    { id = 30744, name = "Draenic Leather Pack", slots = 14, type = "Bag", family = "General", quality = 2, itemLevel = 60, requiredLevel = 0 },
    { id = 43345, name = "Dragon Hide Bag", slots = 22, type = "Bag", family = "General", quality = 4, itemLevel = 80, requiredLevel = 0 },
    { id = 44447, name = "Dragonscale Ammo Pouch", slots = 28, type = "Ammo Pouch", family = "Bullets", quality = 3, itemLevel = 75, requiredLevel = 75 },
    { id = 21194, name = "D'Sak's Big Sack", slots = 32, type = "Ammo Container", family = "Arrows/Bullets", quality = 3, itemLevel = 62, requiredLevel = 0 },
    { id = 21193, name = "D'Sak's Sack", slots = 30, type = "Ammo Container", family = "Arrows/Bullets", quality = 3, itemLevel = 62, requiredLevel = 0 },
    { id = 21195, name = "D'Sak's Sacktastic", slots = 36, type = "Ammo Container", family = "Arrows/Bullets", quality = 3, itemLevel = 62, requiredLevel = 0 },
    { id = 21313, name = "D'Sak's Small bag", slots = 12, type = "Ammo Container", family = "Arrows/Bullets", quality = 3, itemLevel = 62, requiredLevel = 0 },
    { id = 21872, name = "Ebon Shadowbag", slots = 28, type = "Soul Bag", family = "Soul Shards", quality = 3, itemLevel = 75, requiredLevel = 0 },
    { id = 45773, name = "Emerald Bag", slots = 32, type = "Herb Bag", family = "Herbs", quality = 3, itemLevel = 80, requiredLevel = 0 },
    { id = 23389, name = "Empty Draenei Supply Pouch", slots = 4, type = "Bag", family = "General", quality = 1, itemLevel = 5, requiredLevel = 0 },
    { id = 22246, name = "Enchanted Mageweave Pouch", slots = 16, type = "Enchanting Bag", family = "Enchanting", quality = 2, itemLevel = 45, requiredLevel = 0 },
    { id = 22248, name = "Enchanted Runecloth Bag", slots = 20, type = "Enchanting Bag", family = "Enchanting", quality = 2, itemLevel = 55, requiredLevel = 0 },
    { id = 30748, name = "Enchanter's Satchel", slots = 20, type = "Enchanting Bag", family = "Enchanting", quality = 2, itemLevel = 60, requiredLevel = 0 },
    { id = 49295, name = "Enlarged Onyxia Hide Backpack", slots = 22, type = "Bag", family = "General", quality = 4, itemLevel = 55, requiredLevel = 0 },
    { id = 10683, name = "Explorer's Knapsack", slots = 16, type = "Bag", family = "General", quality = 1, itemLevel = 55, requiredLevel = 0 },
    { id = 11324, name = "Explorer's Knapsack", slots = 14, type = "Bag", family = "General", quality = 1, itemLevel = 45, requiredLevel = 0 },
    { id = 16057, name = "Explorer's Knapsack", slots = 12, type = "Bag", family = "General", quality = 1, itemLevel = 35, requiredLevel = 0 },
    { id = 23774, name = "Fel Iron Toolbox", slots = 24, type = "Engineering Bag", family = "Engineering", quality = 2, itemLevel = 65, requiredLevel = 0 },
    { id = 932, name = "Fel Steed Saddlebags", slots = 10, type = "Bag", family = "General", quality = 1, itemLevel = 25, requiredLevel = 0 },
    { id = 21341, name = "Felcloth Bag", slots = 24, type = "Soul Bag", family = "Soul Shards", quality = 3, itemLevel = 57, requiredLevel = 0 },
    { id = 23162, name = "Foror's Crate of Endless Resist Gear Storage", slots = 36, type = "Bag", family = "General", quality = 1, itemLevel = 60, requiredLevel = 0 },
    { id = 41599, name = "Frostweave Bag", slots = 20, type = "Bag", family = "General", quality = 2, itemLevel = 80, requiredLevel = 0 },
    { id = 30747, name = "Gem Pouch", slots = 20, type = "Gem Bag", family = "Gems", quality = 2, itemLevel = 60, requiredLevel = 0 },
    { id = 41600, name = "Glacial Bag", slots = 22, type = "Bag", family = "General", quality = 3, itemLevel = 80, requiredLevel = 0 },
    { id = 3233, name = "Gnoll Hide Sack", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 19320, name = "Gnoll Skin Bandolier", slots = 16, type = "Ammo Pouch", family = "Bullets", quality = 3, itemLevel = 60, requiredLevel = 55 },
    { id = 5573, name = "Green Leather Bag", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 5764, name = "Green Silk Pack", slots = 10, type = "Bag", family = "General", quality = 1, itemLevel = 25, requiredLevel = 0 },
    { id = 4241, name = "Green Woolen Bag", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 1729, name = "Gunnysack of the Night Watch", slots = 10, type = "Bag", family = "General", quality = 1, itemLevel = 25, requiredLevel = 0 },
    { id = 27680, name = "Halaani Bag", slots = 18, type = "Bag", family = "General", quality = 3, itemLevel = 60, requiredLevel = 0 },
    { id = 4930, name = "Handmade Leather Bag", slots = 6, type = "Bag", family = "General", quality = 1, itemLevel = 5, requiredLevel = 0 },
    { id = 11845, name = "Handmade Leather Bag", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 1, requiredLevel = 0 },
    { id = 19319, name = "Harpy Hide Quiver", slots = 16, type = "Quiver", family = "Arrows", quality = 3, itemLevel = 60, requiredLevel = 55 },
    { id = 4497, name = "Heavy Brown Bag", slots = 10, type = "Bag", family = "General", quality = 1, itemLevel = 25, requiredLevel = 0 },
    { id = 7372, name = "Heavy Leather Ammo Pouch", slots = 14, type = "Ammo Pouch", family = "Bullets", quality = 2, itemLevel = 35, requiredLevel = 30 },
    { id = 7371, name = "Heavy Quiver", slots = 14, type = "Quiver", family = "Arrows", quality = 2, itemLevel = 35, requiredLevel = 30 },
    { id = 30745, name = "Heavy Toolbox", slots = 20, type = "Engineering Bag", family = "Engineering", quality = 2, itemLevel = 60, requiredLevel = 0 },
    { id = 22250, name = "Herb Pouch", slots = 12, type = "Herb Bag", family = "Herbs", quality = 2, itemLevel = 20, requiredLevel = 0 },
    { id = 4499, name = "Huge Brown Sack", slots = 12, type = "Bag", family = "General", quality = 1, itemLevel = 35, requiredLevel = 0 },
    { id = 3574, name = "Hunting Ammo Sack", slots = 10, type = "Ammo Pouch", family = "Bullets", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 3573, name = "Hunting Quiver", slots = 10, type = "Quiver", family = "Arrows", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 21843, name = "Imbued Netherweave Bag", slots = 18, type = "Bag", family = "General", quality = 2, itemLevel = 68, requiredLevel = 0 },
    { id = 33117, name = "Jack-o'-Lantern", slots = 18, type = "Bag", family = "General", quality = 3, itemLevel = 1, requiredLevel = 60 },
    { id = 6756, name = "Jewelry Box", slots = 6, type = "Bag", family = "General", quality = 1, itemLevel = 5, requiredLevel = 0 },
    { id = 3914, name = "Journeyman's Backpack", slots = 14, type = "Bag", family = "General", quality = 1, itemLevel = 45, requiredLevel = 0 },
    { id = 34099, name = "Knothide Ammo Pouch", slots = 20, type = "Ammo Pouch", family = "Bullets", quality = 2, itemLevel = 70, requiredLevel = 60 },
    { id = 34100, name = "Knothide Quiver", slots = 20, type = "Quiver", family = "Arrows", quality = 2, itemLevel = 70, requiredLevel = 60 },
    { id = 5081, name = "Kodo Hide Bag", slots = 6, type = "Bag", family = "General", quality = 1, itemLevel = 5, requiredLevel = 0 },
    { id = 804, name = "Large Blue Sack", slots = 10, type = "Bag", family = "General", quality = 1, itemLevel = 25, requiredLevel = 0 },
    { id = 5576, name = "Large Brown Sack", slots = 10, type = "Bag", family = "General", quality = 1, itemLevel = 25, requiredLevel = 0 },
    { id = 5575, name = "Large Green Sack", slots = 10, type = "Bag", family = "General", quality = 1, itemLevel = 25, requiredLevel = 0 },
    { id = 1725, name = "Large Knapsack", slots = 12, type = "Bag", family = "General", quality = 1, itemLevel = 35, requiredLevel = 0 },
    { id = 6754, name = "Large Moneybag", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 1014, name = "Large Moneybag (old)", slots = 10, type = "Bag", family = "General", quality = 1, itemLevel = 1, requiredLevel = 0 },
    { id = 857, name = "Large Red Sack", slots = 10, type = "Bag", family = "General", quality = 1, itemLevel = 25, requiredLevel = 0 },
    { id = 933, name = "Large Rucksack", slots = 10, type = "Bag", family = "General", quality = 1, itemLevel = 25, requiredLevel = 0 },
    { id = 34482, name = "Leatherworker's Satchel", slots = 20, type = "Leatherworking Bag", family = "Leatherworking", quality = 2, itemLevel = 65, requiredLevel = 0 },
    { id = 3762, name = "Librarian's Satchel", slots = 12, type = "Bag", family = "General", quality = 1, itemLevel = 35, requiredLevel = 0 },
    { id = 7278, name = "Light Leather Quiver", slots = 8, type = "Quiver", family = "Arrows", quality = 1, itemLevel = 5, requiredLevel = 1 },
    { id = 2101, name = "Light Quiver", slots = 6, type = "Quiver", family = "Arrows", quality = 1, itemLevel = 1, requiredLevel = 1 },
    { id = 4238, name = "Linen Bag", slots = 6, type = "Bag", family = "General", quality = 1, itemLevel = 5, requiredLevel = 0 },
    { id = 10050, name = "Mageweave Bag", slots = 12, type = "Bag", family = "General", quality = 1, itemLevel = 35, requiredLevel = 0 },
    { id = 22976, name = "Magister's Pouch", slots = 4, type = "Bag", family = "General", quality = 1, itemLevel = 1, requiredLevel = 0 },
    { id = 38347, name = "Mammoth Mining Bag", slots = 32, type = "Mining Bag", family = "Mining", quality = 3, itemLevel = 75, requiredLevel = 0 },
    { id = 11362, name = "Medium Quiver", slots = 10, type = "Quiver", family = "Arrows", quality = 1, itemLevel = 15, requiredLevel = 10 },
    { id = 11363, name = "Medium Shot Pouch", slots = 10, type = "Ammo Pouch", family = "Bullets", quality = 1, itemLevel = 15, requiredLevel = 10 },
    { id = 30746, name = "Mining Sack", slots = 20, type = "Mining Bag", family = "Mining", quality = 2, itemLevel = 60, requiredLevel = 0 },
    { id = 14155, name = "Mooncloth Bag", slots = 16, type = "Bag", family = "General", quality = 2, itemLevel = 60, requiredLevel = 0 },
    { id = 1470, name = "Murloc Skin Bag", slots = 10, type = "Bag", family = "General", quality = 1, itemLevel = 25, requiredLevel = 0 },
    { id = 38225, name = "Mycah's Botanical Bag", slots = 28, type = "Herb Bag", family = "Herbs", quality = 3, itemLevel = 75, requiredLevel = 0 },
    { id = 41598, name = "Mysterious Bag", slots = 32, type = "Enchanting Bag", family = "Enchanting", quality = 3, itemLevel = 80, requiredLevel = 0 },
    { id = 44448, name = "Nerubian Reinforced Quiver", slots = 28, type = "Quiver", family = "Arrows", quality = 3, itemLevel = 75, requiredLevel = 75 },
    { id = 34106, name = "Netherscale Ammo Pouch", slots = 24, type = "Ammo Pouch", family = "Bullets", quality = 3, itemLevel = 70, requiredLevel = 70 },
    { id = 21841, name = "Netherweave Bag", slots = 16, type = "Bag", family = "General", quality = 2, itemLevel = 63, requiredLevel = 0 },
    { id = 23852, name = "Nolkai's Bag", slots = 8, type = "Bag", family = "General", quality = 2, itemLevel = 15, requiredLevel = 0 },
    { id = 1537, name = "Old Blanchy's Feed Pouch", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 1, requiredLevel = 0 },
    { id = 4957, name = "Old Moneybag", slots = 6, type = "Bag", family = "General", quality = 1, itemLevel = 5, requiredLevel = 0 },
    { id = 17966, name = "Onyxia Hide Backpack", slots = 18, type = "Bag", family = "General", quality = 2, itemLevel = 55, requiredLevel = 0 },
    { id = 3352, name = "Ooze-covered Bag", slots = 10, type = "Bag", family = "General", quality = 1, itemLevel = 25, requiredLevel = 0 },
    { id = 44446, name = "Pack of Endless Pockets", slots = 32, type = "Inscription Bag", family = "Inscription", quality = 3, itemLevel = 75, requiredLevel = 0 },
    { id = 19914, name = "Panther Hide Sack", slots = 18, type = "Bag", family = "General", quality = 3, itemLevel = 55, requiredLevel = 0 },
    { id = 50316, name = "Papa's Brand New Bag", slots = 22, type = "Bag", family = "General", quality = 4, itemLevel = 80, requiredLevel = 0 },
    { id = 50317, name = "Papa's New Bag", slots = 20, type = "Bag", family = "General", quality = 4, itemLevel = 80, requiredLevel = 0 },
    { id = 37606, name = "Penny Pouch", slots = 1, type = "Bag", family = "General", quality = 1, itemLevel = 0, requiredLevel = 0 },
    { id = 34845, name = "Pit Lord's Satchel", slots = 20, type = "Bag", family = "General", quality = 4, itemLevel = 70, requiredLevel = 0 },
    { id = 51809, name = "Portable Hole", slots = 24, type = "Bag", family = "General", quality = 4, itemLevel = 80, requiredLevel = 0 },
    { id = 21876, name = "Primal Mooncloth Bag", slots = 20, type = "Bag", family = "General", quality = 3, itemLevel = 70, requiredLevel = 0 },
    { id = 20400, name = "Pumpkin Bag", slots = 16, type = "Bag", family = "General", quality = 2, itemLevel = 1, requiredLevel = 0 },
    { id = 8217, name = "Quickdraw Quiver", slots = 16, type = "Quiver", family = "Arrows", quality = 2, itemLevel = 45, requiredLevel = 40 },
    { id = 34105, name = "Quiver of a Thousand Feathers", slots = 24, type = "Quiver", family = "Arrows", quality = 3, itemLevel = 70, requiredLevel = 70 },
    { id = 3605, name = "Quiver of the Night Watch", slots = 12, type = "Quiver", family = "Arrows", quality = 2, itemLevel = 25, requiredLevel = 0 },
    { id = 1623, name = "Raptor Skin Pouch", slots = 12, type = "Bag", family = "General", quality = 1, itemLevel = 35, requiredLevel = 0 },
    { id = 2657, name = "Red Leather Bag", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 5762, name = "Red Linen Bag", slots = 6, type = "Bag", family = "General", quality = 1, itemLevel = 5, requiredLevel = 0 },
    { id = 10051, name = "Red Mageweave Bag", slots = 12, type = "Bag", family = "General", quality = 1, itemLevel = 35, requiredLevel = 0 },
    { id = 5763, name = "Red Woolen Bag", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 29540, name = "Reinforced Mining Bag", slots = 28, type = "Mining Bag", family = "Mining", quality = 2, itemLevel = 65, requiredLevel = 0 },
    { id = 2663, name = "Ribbly's Bandolier", slots = 16, type = "Ammo Pouch", family = "Bullets", quality = 2, itemLevel = 55, requiredLevel = 50 },
    { id = 2662, name = "Ribbly's Quiver", slots = 16, type = "Quiver", family = "Arrows", quality = 2, itemLevel = 55, requiredLevel = 50 },
    { id = 14046, name = "Runecloth Bag", slots = 14, type = "Bag", family = "General", quality = 1, itemLevel = 52, requiredLevel = 0 },
    { id = 22252, name = "Satchel of Cenarius", slots = 24, type = "Herb Bag", family = "Herbs", quality = 2, itemLevel = 65, requiredLevel = 0 },
    { id = 39489, name = "Scribe's Satchel", slots = 10, type = "Inscription Bag", family = "Inscription", quality = 2, itemLevel = 15, requiredLevel = 0 },
    { id = 2102, name = "Small Ammo Pouch", slots = 6, type = "Ammo Pouch", family = "Bullets", quality = 1, itemLevel = 1, requiredLevel = 1 },
    { id = 5571, name = "Small Black Pouch", slots = 6, type = "Bag", family = "General", quality = 1, itemLevel = 5, requiredLevel = 0 },
    { id = 828, name = "Small Blue Pouch", slots = 6, type = "Bag", family = "General", quality = 1, itemLevel = 5, requiredLevel = 0 },
    { id = 4496, name = "Small Brown Pouch", slots = 6, type = "Bag", family = "General", quality = 1, itemLevel = 5, requiredLevel = 0 },
    { id = 5572, name = "Small Green Pouch", slots = 6, type = "Bag", family = "General", quality = 1, itemLevel = 5, requiredLevel = 0 },
    { id = 7279, name = "Small Leather Ammo Pouch", slots = 8, type = "Ammo Pouch", family = "Bullets", quality = 1, itemLevel = 5, requiredLevel = 1 },
    { id = 5439, name = "Small Quiver", slots = 8, type = "Quiver", family = "Arrows", quality = 1, itemLevel = 5, requiredLevel = 1 },
    { id = 805, name = "Small Red Pouch", slots = 6, type = "Bag", family = "General", quality = 1, itemLevel = 5, requiredLevel = 0 },
    { id = 5441, name = "Small Shot Pouch", slots = 8, type = "Ammo Pouch", family = "Bullets", quality = 1, itemLevel = 5, requiredLevel = 1 },
    { id = 4245, name = "Small Silk Pack", slots = 10, type = "Bag", family = "General", quality = 1, itemLevel = 25, requiredLevel = 0 },
    { id = 22243, name = "Small Soul Pouch", slots = 12, type = "Soul Bag", family = "Soul Shards", quality = 2, itemLevel = 20, requiredLevel = 0 },
    { id = 29118, name = "Smuggler's Ammo Pouch", slots = 18, type = "Ammo Pouch", family = "Bullets", quality = 3, itemLevel = 103, requiredLevel = 68 },
    { id = 6446, name = "Snakeskin Bag", slots = 10, type = "Bag", family = "General", quality = 3, itemLevel = 25, requiredLevel = 0 },
    { id = 21340, name = "Soul Pouch", slots = 20, type = "Soul Bag", family = "Soul Shards", quality = 2, itemLevel = 52, requiredLevel = 0 },
    { id = 21858, name = "Spellfire Bag", slots = 28, type = "Enchanting Bag", family = "Enchanting", quality = 3, itemLevel = 95, requiredLevel = 0 },
    { id = 1652, name = "Sturdy Lunchbox", slots = 12, type = "Bag", family = "General", quality = 1, itemLevel = 35, requiredLevel = 0 },
    { id = 35516, name = "Sun Touched Satchel", slots = 20, type = "Bag", family = "General", quality = 3, itemLevel = 70, requiredLevel = 0 },
    { id = 20474, name = "Sunstrider Book Satchel", slots = 4, type = "Bag", family = "General", quality = 1, itemLevel = 1, requiredLevel = 0 },
    { id = 22679, name = "Supply Bag", slots = 18, type = "Bag", family = "General", quality = 3, itemLevel = 60, requiredLevel = 0 },
    { id = 34067, name = "Tattered Hexcloth Sack", slots = 20, type = "Bag", family = "General", quality = 3, itemLevel = 70, requiredLevel = 0 },
    { id = 21857, name = "Test Herb Bag", slots = 20, type = "Ammo Pouch", family = "Bullets/Soul Shards", quality = 2, itemLevel = 52, requiredLevel = 0 },
    { id = 9587, name = "Thawpelt Sack", slots = 14, type = "Bag", family = "General", quality = 1, itemLevel = 45, requiredLevel = 0 },
    { id = 8218, name = "Thick Leather Ammo Pouch", slots = 16, type = "Ammo Pouch", family = "Bullets", quality = 2, itemLevel = 45, requiredLevel = 40 },
    { id = 23775, name = "Titanium Toolbox", slots = 32, type = "Engineering Bag", family = "Engineering", quality = 3, itemLevel = 75, requiredLevel = 0 },
    { id = 38399, name = "Trapper's Traveling Pack", slots = 28, type = "Leatherworking Bag", family = "Leatherworking", quality = 3, itemLevel = 80, requiredLevel = 0 },
    { id = 4500, name = "Traveler's Backpack", slots = 16, type = "Bag", family = "General", quality = 2, itemLevel = 55, requiredLevel = 0 },
    { id = 1685, name = "Troll-hide Bag", slots = 14, type = "Bag", family = "General", quality = 1, itemLevel = 45, requiredLevel = 0 },
    { id = 11742, name = "Wayfarer's Knapsack", slots = 16, type = "Bag", family = "General", quality = 2, itemLevel = 55, requiredLevel = 0 },
    { id = 5574, name = "White Leather Bag", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 2082, name = "Wizbang's Gunnysack", slots = 6, type = "Bag", family = "General", quality = 1, itemLevel = 5, requiredLevel = 0 },
    { id = 5603, name = "Wizbang's Gunnysack", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 4240, name = "Woolen Bag", slots = 8, type = "Bag", family = "General", quality = 1, itemLevel = 15, requiredLevel = 0 },
    { id = 29144, name = "Worg Hide Quiver", slots = 18, type = "Quiver", family = "Arrows", quality = 3, itemLevel = 109, requiredLevel = 68 },
    { id = 22233, name = "Zigris' Footlocker", slots = 16, type = "Bag", family = "General", quality = 2, itemLevel = 60, requiredLevel = 0 },
}
