-- Mount spell data derived from the WotLKDB Mounts spell category (cat -5, skill 777).
-- Generated for offline in-game browsing because the WotLK addon sandbox cannot make HTTP requests.
GMCC_MOUNT_SPELLS = {
    { id = 458, name = "Brown Horse", speed = "+60%", movement = "Ground", level = 1 },
    { id = 459, name = "Gray Wolf", speed = "+60%", movement = "Ground", level = 1 },
    { id = 468, name = "White Stallion", speed = "+60%", movement = "Ground", level = 1 },
    { id = 470, name = "Black Stallion", speed = "+60%", movement = "Ground", level = 1 },
    { id = 471, name = "Palamino", speed = "+60%", movement = "Ground", level = 1 },
    { id = 472, name = "Pinto", speed = "+60%", movement = "Ground", level = 1 },
    { id = 578, name = "Black Wolf", speed = "+60%", movement = "Ground", level = 1 },
    { id = 579, name = "Red Wolf", speed = "+100%", movement = "Ground", level = 1 },
    { id = 580, name = "Timber Wolf", speed = "+60%", movement = "Ground", level = 1 },
    { id = 581, name = "Winter Wolf", speed = "+60%", movement = "Ground", level = 1 },
    { id = 3363, name = "Nether Drake", speed = "+310%", movement = "Flying", level = 1 },
    { id = 5784, name = "Felsteed", speed = "+60%", movement = "Ground", level = 20, class = "Warlock" },
    { id = 6648, name = "Chestnut Mare", speed = "+60%", movement = "Ground", level = 1 },
    { id = 6653, name = "Dire Wolf", speed = "+60%", movement = "Ground", level = 1 },
    { id = 6654, name = "Brown Wolf", speed = "+60%", movement = "Ground", level = 1 },
    { id = 6777, name = "Gray Ram", speed = "+60%", movement = "Ground", level = 1 },
    { id = 6896, name = "Black Ram", speed = "+60%", movement = "Ground", level = 1 },
    { id = 6897, name = "Blue Ram", speed = "+60%", movement = "Ground", level = 1 },
    { id = 6898, name = "White Ram", speed = "+60%", movement = "Ground", level = 1 },
    { id = 6899, name = "Brown Ram", speed = "+60%", movement = "Ground", level = 1 },
    { id = 8394, name = "Striped Frostsaber", speed = "+60%", movement = "Ground", level = 1 },
    { id = 8395, name = "Emerald Raptor", speed = "+60%", movement = "Ground", level = 1 },
    { id = 8980, name = "Skeletal Horse", speed = "+60%", movement = "Ground", level = 1 },
    { id = 10789, name = "Spotted Frostsaber", speed = "+60%", movement = "Ground", level = 1 },
    { id = 10793, name = "Striped Nightsaber", speed = "+60%", movement = "Ground", level = 1 },
    { id = 10795, name = "Ivory Raptor", speed = "+60%", movement = "Ground", level = 1 },
    { id = 10796, name = "Turquoise Raptor", speed = "+60%", movement = "Ground", level = 1 },
    { id = 10798, name = "Obsidian Raptor", speed = "+60%", movement = "Ground", level = 1 },
    { id = 10799, name = "Violet Raptor", speed = "+60%", movement = "Ground", level = 1 },
    { id = 10873, name = "Red Mechanostrider", speed = "+60%", movement = "Ground", level = 1 },
    { id = 10969, name = "Blue Mechanostrider", speed = "+60%", movement = "Ground", level = 1 },
    { id = 13819, name = "Warhorse", speed = "+60%", movement = "Ground", level = 20, class = "Paladin" },
    { id = 15779, name = "White Mechanostrider Mod B", speed = "+100%", movement = "Ground", level = 1 },
    { id = 15780, name = "Green Mechanostrider", speed = "+60%", movement = "Ground", level = 1 },
    { id = 15781, name = "Steel Mechanostrider", speed = "+60%", movement = "Ground", level = 1 },
    { id = 16055, name = "Black Nightsaber", speed = "+100%", movement = "Ground", level = 1 },
    { id = 16056, name = "Ancient Frostsaber", speed = "+100%", movement = "Ground", level = 1 },
    { id = 16058, name = "Primal Leopard", speed = "+60%", movement = "Ground", level = 1 },
    { id = 16059, name = "Tawny Sabercat", speed = "+60%", movement = "Ground", level = 1 },
    { id = 16060, name = "Golden Sabercat", speed = "+60%", movement = "Ground", level = 1 },
    { id = 16080, name = "Red Wolf", speed = "+100%", movement = "Ground", level = 1 },
    { id = 16081, name = "Winter Wolf", speed = "+100%", movement = "Ground", level = 1 },
    { id = 16082, name = "Palomino", speed = "+100%", movement = "Ground", level = 1 },
    { id = 16083, name = "White Stallion", speed = "+100%", movement = "Ground", level = 1 },
    { id = 16084, name = "Mottled Red Raptor", speed = "+100%", movement = "Ground", level = 1 },
    { id = 17229, name = "Winterspring Frostsaber", speed = "+100%", movement = "Ground", level = 1 },
    { id = 17450, name = "Ivory Raptor", speed = "+100%", movement = "Ground", level = 1 },
    { id = 17453, name = "Green Mechanostrider", speed = "+60%", movement = "Ground", level = 1 },
    { id = 17454, name = "Unpainted Mechanostrider", speed = "+60%", movement = "Ground", level = 1 },
    { id = 17455, name = "Purple Mechanostrider", speed = "+60%", movement = "Ground", level = 1 },
    { id = 17456, name = "Red and Blue Mechanostrider", speed = "+60%", movement = "Ground", level = 1 },
    { id = 17458, name = "Fluorescent Green Mechanostrider", speed = "+60%", movement = "Ground", level = 1 },
    { id = 17459, name = "Icy Blue Mechanostrider Mod A", speed = "+100%", movement = "Ground", level = 1 },
    { id = 17460, name = "Frost Ram", speed = "+100%", movement = "Ground", level = 1 },
    { id = 17461, name = "Black Ram", speed = "+100%", movement = "Ground", level = 1 },
    { id = 17462, name = "Red Skeletal Horse", speed = "+60%", movement = "Ground", level = 1 },
    { id = 17463, name = "Blue Skeletal Horse", speed = "+60%", movement = "Ground", level = 1 },
    { id = 17464, name = "Brown Skeletal Horse", speed = "+60%", movement = "Ground", level = 1 },
    { id = 17465, name = "Green Skeletal Warhorse", speed = "+100%", movement = "Ground", level = 1 },
    { id = 17481, name = "Rivendare's Deathcharger", speed = "+100%", movement = "Ground", level = 1 },
    { id = 18363, name = "Riding Kodo", speed = "+60%", movement = "Ground", level = 1 },
    { id = 18989, name = "Gray Kodo", speed = "+60%", movement = "Ground", level = 1 },
    { id = 18990, name = "Brown Kodo", speed = "+60%", movement = "Ground", level = 1 },
    { id = 18991, name = "Green Kodo", speed = "+100%", movement = "Ground", level = 1 },
    { id = 18992, name = "Teal Kodo", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23161, name = "Dreadsteed", speed = "+100%", movement = "Ground", level = 40, class = "Warlock" },
    { id = 23214, name = "Charger", speed = "+100%", movement = "Ground", level = 40, class = "Paladin" },
    { id = 23219, name = "Swift Mistsaber", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23220, name = "Swift Dawnsaber", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23221, name = "Swift Frostsaber", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23222, name = "Swift Yellow Mechanostrider", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23223, name = "Swift White Mechanostrider", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23225, name = "Swift Green Mechanostrider", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23227, name = "Swift Palomino", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23228, name = "Swift White Steed", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23229, name = "Swift Brown Steed", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23238, name = "Swift Brown Ram", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23239, name = "Swift Gray Ram", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23240, name = "Swift White Ram", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23241, name = "Swift Blue Raptor", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23242, name = "Swift Olive Raptor", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23243, name = "Swift Orange Raptor", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23246, name = "Purple Skeletal Warhorse", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23247, name = "Great White Kodo", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23248, name = "Great Gray Kodo", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23249, name = "Great Brown Kodo", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23250, name = "Swift Brown Wolf", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23251, name = "Swift Timber Wolf", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23252, name = "Swift Gray Wolf", speed = "+100%", movement = "Ground", level = 1 },
    { id = 23338, name = "Swift Stormsaber", speed = "+100%", movement = "Ground", level = 1 },
    { id = 24242, name = "Swift Razzashi Raptor", speed = "+100%", movement = "Ground", level = 1 },
    { id = 24252, name = "Swift Zulian Tiger", speed = "+100%", movement = "Ground", level = 1 },
    { id = 25953, name = "Blue Qiraji Battle Tank", speed = "+100%", movement = "Ground", level = 1 },
    { id = 26054, name = "Red Qiraji Battle Tank", speed = "+100%", movement = "Ground", level = 1 },
    { id = 26055, name = "Yellow Qiraji Battle Tank", speed = "+100%", movement = "Ground", level = 1 },
    { id = 26056, name = "Green Qiraji Battle Tank", speed = "+100%", movement = "Ground", level = 1 },
    { id = 26656, name = "Black Qiraji Battle Tank", speed = "+100%", movement = "Ground", level = 1 },
    { id = 28828, name = "Nether Drake", speed = "+300%", movement = "Unknown", level = 1 },
    { id = 29059, name = "Naxxramas Deathcharger", speed = "+100%", movement = "Ground", level = 1 },
    { id = 30174, name = "Riding Turtle", speed = "+0%", movement = "Unknown", level = 1 },
    { id = 32235, name = "Golden Gryphon", speed = "+150%", movement = "Flying", level = 1 },
    { id = 32239, name = "Ebon Gryphon", speed = "+150%", movement = "Flying", level = 1 },
    { id = 32240, name = "Snowy Gryphon", speed = "+150%", movement = "Flying", level = 1 },
    { id = 32242, name = "Swift Blue Gryphon", speed = "+280%", movement = "Flying", level = 1 },
    { id = 32243, name = "Tawny Wind Rider", speed = "+150%", movement = "Flying", level = 1 },
    { id = 32244, name = "Blue Wind Rider", speed = "+150%", movement = "Flying", level = 1 },
    { id = 32245, name = "Green Wind Rider", speed = "+150%", movement = "Flying", level = 1 },
    { id = 32246, name = "Swift Red Wind Rider", speed = "+280%", movement = "Flying", level = 1 },
    { id = 32289, name = "Swift Red Gryphon", speed = "+280%", movement = "Flying", level = 1 },
    { id = 32290, name = "Swift Green Gryphon", speed = "+280%", movement = "Flying", level = 1 },
    { id = 32292, name = "Swift Purple Gryphon", speed = "+280%", movement = "Flying", level = 1 },
    { id = 32295, name = "Swift Green Wind Rider", speed = "+280%", movement = "Flying", level = 1 },
    { id = 32296, name = "Swift Yellow Wind Rider", speed = "+280%", movement = "Flying", level = 1 },
    { id = 32297, name = "Swift Purple Wind Rider", speed = "+280%", movement = "Flying", level = 1 },
    { id = 32345, name = "Peep the Phoenix Mount", speed = "+310%", movement = "Flying", level = 1 },
    { id = 33630, name = "Blue Mechanostrider", speed = "+60%", movement = "Ground", level = 1 },
    { id = 33660, name = "Swift Pink Hawkstrider", speed = "+100%", movement = "Ground", level = 1 },
    { id = 34406, name = "Brown Elekk", speed = "+60%", movement = "Ground", level = 1 },
    { id = 34407, name = "Great Elite Elekk", speed = "+100%", movement = "Ground", level = 1 },
    { id = 34767, name = "Summon Charger", speed = "+100%", movement = "Ground", level = 40, class = "Paladin" },
    { id = 34769, name = "Summon Warhorse", speed = "+60%", movement = "Ground", level = 20, class = "Paladin" },
    { id = 34790, name = "Dark War Talbuk", speed = "+100%", movement = "Ground", level = 1 },
    { id = 34795, name = "Red Hawkstrider", speed = "+60%", movement = "Ground", level = 1 },
    { id = 34896, name = "Cobalt War Talbuk", speed = "+100%", movement = "Ground", level = 1 },
    { id = 34897, name = "White War Talbuk", speed = "+100%", movement = "Ground", level = 1 },
    { id = 34898, name = "Silver War Talbuk", speed = "+100%", movement = "Ground", level = 1 },
    { id = 34899, name = "Tan War Talbuk", speed = "+100%", movement = "Ground", level = 1 },
    { id = 35018, name = "Purple Hawkstrider", speed = "+60%", movement = "Ground", level = 1 },
    { id = 35020, name = "Blue Hawkstrider", speed = "+60%", movement = "Ground", level = 1 },
    { id = 35022, name = "Black Hawkstrider", speed = "+60%", movement = "Ground", level = 1 },
    { id = 35025, name = "Swift Green Hawkstrider", speed = "+100%", movement = "Ground", level = 1 },
    { id = 35027, name = "Swift Purple Hawkstrider", speed = "+100%", movement = "Ground", level = 1 },
    { id = 35710, name = "Gray Elekk", speed = "+60%", movement = "Ground", level = 1 },
    { id = 35711, name = "Purple Elekk", speed = "+60%", movement = "Ground", level = 1 },
    { id = 35712, name = "Great Green Elekk", speed = "+100%", movement = "Ground", level = 1 },
    { id = 35713, name = "Great Blue Elekk", speed = "+100%", movement = "Ground", level = 1 },
    { id = 35714, name = "Great Purple Elekk", speed = "+100%", movement = "Ground", level = 1 },
    { id = 36702, name = "Fiery Warhorse", speed = "+100%", movement = "Ground", level = 1 },
    { id = 37015, name = "Swift Nether Drake", speed = "+310%", movement = "Flying", level = 1 },
    { id = 39315, name = "Cobalt Riding Talbuk", speed = "+100%", movement = "Ground", level = 1 },
    { id = 39316, name = "Dark Riding Talbuk", speed = "+100%", movement = "Ground", level = 1 },
    { id = 39317, name = "Silver Riding Talbuk", speed = "+100%", movement = "Ground", level = 1 },
    { id = 39318, name = "Tan Riding Talbuk", speed = "+100%", movement = "Ground", level = 1 },
    { id = 39319, name = "White Riding Talbuk", speed = "+100%", movement = "Ground", level = 1 },
    { id = 39798, name = "Green Riding Nether Ray", speed = "+280%", movement = "Flying", level = 1 },
    { id = 39800, name = "Red Riding Nether Ray", speed = "+280%", movement = "Flying", level = 1 },
    { id = 39801, name = "Purple Riding Nether Ray", speed = "+280%", movement = "Flying", level = 1 },
    { id = 39802, name = "Silver Riding Nether Ray", speed = "+280%", movement = "Flying", level = 1 },
    { id = 39803, name = "Blue Riding Nether Ray", speed = "+280%", movement = "Flying", level = 1 },
    { id = 40192, name = "Ashes of Al'ar", speed = "+310%", movement = "Flying", level = 1 },
    { id = 41252, name = "Raven Lord", speed = "+100%", movement = "Ground", level = 1 },
    { id = 41513, name = "Onyx Netherwing Drake", speed = "+280%", movement = "Flying", level = 1 },
    { id = 41514, name = "Azure Netherwing Drake", speed = "+280%", movement = "Flying", level = 1 },
    { id = 41515, name = "Cobalt Netherwing Drake", speed = "+280%", movement = "Flying", level = 1 },
    { id = 41516, name = "Purple Netherwing Drake", speed = "+280%", movement = "Flying", level = 1 },
    { id = 41517, name = "Veridian Netherwing Drake", speed = "+280%", movement = "Flying", level = 1 },
    { id = 41518, name = "Violet Netherwing Drake", speed = "+280%", movement = "Flying", level = 1 },
    { id = 42776, name = "Spectral Tiger", speed = "+60%", movement = "Ground", level = 1 },
    { id = 42777, name = "Swift Spectral Tiger", speed = "+100%", movement = "Ground", level = 1 },
    { id = 43688, name = "Amani War Bear", speed = "+100%", movement = "Ground", level = 1 },
    { id = 43810, name = "Frost Wyrm", speed = "+280%", movement = "Flying", level = 1 },
    { id = 43899, name = "Brewfest Ram", speed = "+60%", movement = "Ground", level = 1 },
    { id = 43900, name = "Swift Brewfest Ram", speed = "+100%", movement = "Ground", level = 1 },
    { id = 43927, name = "Cenarion War Hippogryph", speed = "+280%", movement = "Flying", level = 1 },
    { id = 44151, name = "Turbo-Charged Flying Machine", speed = "+280%", movement = "Flying", level = 1 },
    { id = 44153, name = "Flying Machine", speed = "+150%", movement = "Flying", level = 1 },
    { id = 44317, name = "Merciless Nether Drake", speed = "+310%", movement = "Flying", level = 1 },
    { id = 44744, name = "Merciless Nether Drake", speed = "+310%", movement = "Flying", level = 1 },
    { id = 46197, name = "X-51 Nether-Rocket", speed = "+150%", movement = "Flying", level = 1 },
    { id = 46199, name = "X-51 Nether-Rocket X-TREME", speed = "+280%", movement = "Flying", level = 1 },
    { id = 46628, name = "Swift White Hawkstrider", speed = "+100%", movement = "Ground", level = 1 },
    { id = 47037, name = "Swift War  Elekk", speed = "+100%", movement = "Ground", level = 1 },
    { id = 48025, name = "Headless Horseman's Mount", speed = "?", movement = "Unknown", level = 0 },
    { id = 48778, name = "Acherus Deathcharger", speed = "+100%", movement = "Ground", level = 55, class = "Death Knight" },
    { id = 48954, name = "Swift Zhevra", speed = "+100%", movement = "Ground", level = 1 },
    { id = 49193, name = "Vengeful Nether Drake", speed = "+310%", movement = "Flying", level = 1 },
    { id = 49322, name = "Swift Zhevra", speed = "+100%", movement = "Ground", level = 1 },
    { id = 49378, name = "Brewfest Riding Kodo", speed = "+60%", movement = "Ground", level = 1 },
    { id = 49379, name = "Great Brewfest Kodo", speed = "+100%", movement = "Ground", level = 1 },
    { id = 50869, name = "Brewfest Kodo", speed = "+60%", movement = "Ground", level = 1 },
    { id = 50870, name = "Brewfest Ram", speed = "+60%", movement = "Ground", level = 1 },
    { id = 51412, name = "Big Battle Bear", speed = "+100%", movement = "Ground", level = 1 },
    { id = 51960, name = "Frost Wyrm Mount", speed = "+280%", movement = "Flying", level = 1 },
    { id = 54729, name = "Winged Steed of the Ebon Blade", speed = "?", movement = "Unknown", level = 1 },
    { id = 54753, name = "White Polar Bear", speed = "+100%", movement = "Ground", level = 1 },
    { id = 55531, name = "Mechano-hog", speed = "+100%", movement = "Ground", level = 1 },
    { id = 58615, name = "Brutal Nether Drake", speed = "+310%", movement = "Flying", level = 1 },
    { id = 58983, name = "Big Blizzard Bear", speed = "?", movement = "Unknown", level = 0 },
    { id = 59567, name = "Azure Drake", speed = "+280%", movement = "Flying", level = 1 },
    { id = 59568, name = "Blue Drake", speed = "+280%", movement = "Flying", level = 1 },
    { id = 59569, name = "Bronze Drake", speed = "+280%", movement = "Flying", level = 1 },
    { id = 59570, name = "Red Drake", speed = "+280%", movement = "Flying", level = 1 },
    { id = 59571, name = "Twilight Drake", speed = "+280%", movement = "Flying", level = 1 },
    { id = 59572, name = "Black Polar Bear", speed = "+100%", movement = "Ground", level = 1 },
    { id = 59573, name = "Brown Polar Bear", speed = "+100%", movement = "Ground", level = 1 },
    { id = 59650, name = "Black Drake", speed = "+280%", movement = "Flying", level = 1 },
    { id = 59785, name = "Black War Mammoth", speed = "+100%", movement = "Ground", level = 1 },
    { id = 59788, name = "Black War Mammoth", speed = "+100%", movement = "Ground", level = 1 },
    { id = 59791, name = "Wooly Mammoth", speed = "+100%", movement = "Ground", level = 1 },
    { id = 59793, name = "Wooly Mammoth", speed = "+100%", movement = "Ground", level = 1 },
    { id = 59797, name = "Ice Mammoth", speed = "+100%", movement = "Ground", level = 1 },
    { id = 59799, name = "Ice Mammoth", speed = "+100%", movement = "Ground", level = 1 },
    { id = 59802, name = "Grand Ice Mammoth", speed = "+100%", movement = "Ground", level = 1 },
    { id = 59804, name = "Grand Ice Mammoth", speed = "+100%", movement = "Ground", level = 1 },
    { id = 59961, name = "Red Proto-Drake", speed = "+280%", movement = "Flying", level = 1 },
    { id = 59976, name = "Black Proto-Drake", speed = "+310%", movement = "Flying", level = 1 },
    { id = 59996, name = "Blue Proto-Drake", speed = "+280%", movement = "Flying", level = 1 },
    { id = 60002, name = "Time-Lost Proto-Drake", speed = "+280%", movement = "Flying", level = 1 },
    { id = 60021, name = "Plagued Proto-Drake", speed = "+310%", movement = "Flying", level = 1 },
    { id = 60024, name = "Violet Proto-Drake", speed = "+310%", movement = "Flying", level = 1 },
    { id = 60025, name = "Albino Drake", speed = "+280%", movement = "Flying", level = 1 },
    { id = 60114, name = "Armored Brown Bear", speed = "+100%", movement = "Ground", level = 1 },
    { id = 60116, name = "Armored Brown Bear", speed = "+100%", movement = "Ground", level = 1 },
    { id = 60118, name = "Black War Bear", speed = "+100%", movement = "Ground", level = 1 },
    { id = 60119, name = "Black War Bear", speed = "+100%", movement = "Ground", level = 1 },
    { id = 60136, name = "Grand Caravan Mammoth", speed = "+100%", movement = "Ground", level = 1 },
    { id = 60140, name = "Grand Caravan Mammoth", speed = "+100%", movement = "Ground", level = 1 },
    { id = 60424, name = "Mekgineer's Chopper", speed = "+100%", movement = "Ground", level = 1 },
    { id = 61229, name = "Armored Snowy Gryphon", speed = "+280%", movement = "Flying", level = 1 },
    { id = 61230, name = "Armored Blue Wind Rider", speed = "+280%", movement = "Flying", level = 1 },
    { id = 61294, name = "Green Proto-Drake", speed = "+280%", movement = "Flying", level = 1 },
    { id = 61309, name = "Magnificent Flying Carpet", speed = "+280%", movement = "Flying", level = 0 },
    { id = 61425, name = "Traveler's Tundra Mammoth", speed = "+100%", movement = "Ground", level = 1 },
    { id = 61442, name = "Swift Mooncloth Carpet", speed = "+0%", movement = "Unknown", level = 0 },
    { id = 61444, name = "Swift Shadoweave Carpet", speed = "+0%", movement = "Unknown", level = 0 },
    { id = 61446, name = "Swift Spellfire Carpet", speed = "+0%", movement = "Unknown", level = 0 },
    { id = 61447, name = "Traveler's Tundra Mammoth", speed = "+100%", movement = "Ground", level = 1 },
    { id = 61451, name = "Flying Carpet", speed = "+150%", movement = "Flying", level = 0 },
    { id = 61465, name = "Grand Black War Mammoth", speed = "+100%", movement = "Ground", level = 1 },
    { id = 61467, name = "Grand Black War Mammoth", speed = "+100%", movement = "Ground", level = 1 },
    { id = 61469, name = "Grand Ice Mammoth", speed = "+100%", movement = "Ground", level = 1 },
    { id = 61470, name = "Grand Ice Mammoth", speed = "+100%", movement = "Ground", level = 1 },
    { id = 61996, name = "Blue Dragonhawk", speed = "+280%", movement = "Flying", level = 1 },
    { id = 61997, name = "Red Dragonhawk", speed = "+280%", movement = "Flying", level = 1 },
    { id = 62048, name = "Black Dragonhawk Mount", speed = "+280%", movement = "Flying", level = 1 },
    { id = 63232, name = "Stormwind Steed", speed = "+100%", movement = "Ground", level = 1 },
    { id = 63635, name = "Darkspear Raptor", speed = "+100%", movement = "Ground", level = 1 },
    { id = 63636, name = "Ironforge Ram", speed = "+100%", movement = "Ground", level = 1 },
    { id = 63637, name = "Darnassian Nightsaber", speed = "+100%", movement = "Ground", level = 1 },
    { id = 63638, name = "Gnomeregan Mechanostrider", speed = "+100%", movement = "Ground", level = 1 },
    { id = 63639, name = "Exodar Elekk", speed = "+100%", movement = "Ground", level = 1 },
    { id = 63640, name = "Orgrimmar Wolf", speed = "+100%", movement = "Ground", level = 1 },
    { id = 63641, name = "Thunder Bluff Kodo", speed = "+100%", movement = "Ground", level = 1 },
    { id = 63642, name = "Silvermoon Hawkstrider", speed = "+100%", movement = "Ground", level = 1 },
    { id = 63643, name = "Forsaken Warhorse", speed = "+100%", movement = "Ground", level = 1 },
    { id = 63796, name = "Mimiron's Head", speed = "+310%", movement = "Flying", level = 1 },
    { id = 63844, name = "Argent Hippogryph", speed = "+280%", movement = "Flying", level = 1 },
    { id = 63956, name = "Ironbound Proto-Drake", speed = "+310%", movement = "Flying", level = 1 },
    { id = 63963, name = "Rusted Proto-Drake", speed = "+310%", movement = "Flying", level = 1 },
    { id = 64656, name = "Blue Skeletal Warhorse", speed = "+100%", movement = "Ground", level = 1 },
    { id = 64657, name = "White Kodo", speed = "+60%", movement = "Ground", level = 1 },
    { id = 64658, name = "Black Wolf", speed = "+60%", movement = "Ground", level = 1 },
    { id = 64659, name = "Venomhide Ravasaur", speed = "+100%", movement = "Ground", level = 1 },
    { id = 64731, name = "Sea Turtle", speed = "+60%", movement = "Aquatic", level = 1 },
    { id = 64927, name = "Deadly Gladiator's Frost Wyrm", speed = "+310%", movement = "Flying", level = 1 },
    { id = 64977, name = "Black Skeletal Horse", speed = "+60%", movement = "Ground", level = 1 },
    { id = 65439, name = "Furious Gladiator's Frost Wyrm", speed = "+310%", movement = "Flying", level = 1 },
    { id = 65637, name = "Great Red Elekk", speed = "+100%", movement = "Ground", level = 1 },
    { id = 65638, name = "Swift Moonsaber", speed = "+100%", movement = "Ground", level = 1 },
    { id = 65639, name = "Swift Red Hawkstrider", speed = "+100%", movement = "Ground", level = 1 },
    { id = 65640, name = "Swift Gray Steed", speed = "+100%", movement = "Ground", level = 1 },
    { id = 65641, name = "Great Golden Kodo", speed = "+100%", movement = "Ground", level = 1 },
    { id = 65642, name = "Turbostrider", speed = "+100%", movement = "Ground", level = 1 },
    { id = 65643, name = "Swift Violet Ram", speed = "+100%", movement = "Ground", level = 1 },
    { id = 65644, name = "Swift Purple Raptor", speed = "+100%", movement = "Ground", level = 1 },
    { id = 65645, name = "White Skeletal Warhorse", speed = "+100%", movement = "Ground", level = 1 },
    { id = 65646, name = "Swift Burgundy Wolf", speed = "+100%", movement = "Ground", level = 1 },
    { id = 65917, name = "Magic Rooster", speed = "?", movement = "Unknown", level = 1 },
    { id = 66087, name = "Silver Covenant Hippogryph", speed = "+280%", movement = "Flying", level = 1 },
    { id = 66088, name = "Sunreaver Dragonhawk", speed = "+280%", movement = "Flying", level = 1 },
    { id = 66090, name = "Quel'dorei Steed", speed = "+100%", movement = "Ground", level = 1 },
    { id = 66091, name = "Sunreaver Hawkstrider", speed = "+100%", movement = "Ground", level = 1 },
    { id = 66122, name = "Magic Rooster", speed = "+100%", movement = "Ground", level = 1 },
    { id = 66123, name = "Magic Rooster", speed = "+100%", movement = "Ground", level = 1 },
    { id = 66124, name = "Magic Rooster", speed = "+100%", movement = "Ground", level = 1 },
    { id = 66846, name = "Ochre Skeletal Warhorse", speed = "+100%", movement = "Ground", level = 1 },
    { id = 66847, name = "Striped Dawnsaber", speed = "+60%", movement = "Ground", level = 1 },
    { id = 66906, name = "Argent Charger", speed = "+100%", movement = "Ground", level = 40 },
    { id = 66907, name = "Argent Warhorse", speed = "+60%", movement = "Ground", level = 20 },
    { id = 67336, name = "Relentless Gladiator's Frost Wyrm", speed = "+310%", movement = "Flying", level = 1 },
    { id = 67466, name = "Argent Warhorse", speed = "+100%", movement = "Ground", level = 1 },
    { id = 68056, name = "Swift Horde Wolf", speed = "+100%", movement = "Ground", level = 1 },
    { id = 68057, name = "Swift Alliance Steed", speed = "+100%", movement = "Ground", level = 1 },
    { id = 68187, name = "Crusader's White Warhorse", speed = "+100%", movement = "Ground", level = 1 },
    { id = 68188, name = "Crusader's Black Warhorse", speed = "+100%", movement = "Ground", level = 1 },
    { id = 69395, name = "Onyxian Drake", speed = "+310%", movement = "Flying", level = 1 },
    { id = 71342, name = "Big Love Rocket", speed = "?", movement = "Unknown", level = 0 },
    { id = 71810, name = "Wrathful Gladiator's Frost Wyrm", speed = "+310%", movement = "Flying", level = 1 },
}
