GMCC_COMMANDS = {
    { cat = "GM", name = "gm", sec = 1, syntax = ".gm [on/off]", help = "Enable, disable, or show GM mode.", args = "[on/off]" },
    { cat = "GM", name = "gm visible", sec = 2, syntax = ".gm visible on/off", help = "Set GM visibility for other players.", args = "on/off" },
    { cat = "GM", name = "gm fly", sec = 2, syntax = ".gm fly on/off", help = "Enable or disable GM flying where supported.", args = "on/off" },
    { cat = "GM", name = "gm chat", sec = 1, syntax = ".gm chat on/off", help = "Enable or disable GM badge in chat.", args = "on/off" },
    { cat = "GM", name = "gm list", sec = 3, syntax = ".gm list", help = "Display online GM accounts and security levels." },
    { cat = "GM", name = "commands", sec = 0, syntax = ".commands", help = "Display available commands for your security level." },
    { cat = "GM", name = "help", sec = 0, syntax = ".help $command", help = "Show server-side help for a command.", args = "$command" },

    { cat = "Items", name = "lookup item", sec = 1, syntax = ".lookup item $itemname", help = "Search items by name.", args = "$itemname" },
    { cat = "Items", name = "lookup item set", sec = 1, syntax = ".lookup itemset $itemname", help = "Search item sets by name.", args = "$itemname" },
    { cat = "Items", name = "additem", sec = 2, syntax = ".additem Optional(playerName/playerGUID) #itemID/[#itemName]/#itemLink #itemCount", help = "Add or remove an item. Negative count removes.", args = "#itemID #count" },
    { cat = "Items", name = "additem set", sec = 2, syntax = ".additemset #itemsetid", help = "Add all items from an item set.", args = "#itemsetid" },
    { cat = "Items", name = "gear repair", sec = 2, syntax = ".gear repair", help = "Repair all selected player's items." },
    { cat = "Items", name = "bags clear", sec = 2, syntax = ".bags clear $itemQuality", help = "Clear bags by item quality or all.", args = "$itemQuality/all" },

    { cat = "Spells", name = "lookup spell", sec = 1, syntax = ".lookup spell $namepart", help = "Search spells by name.", args = "$namepart" },
    { cat = "Spells", name = "lookup spell id", sec = 1, syntax = ".lookup spell id #spellid", help = "Find a spell name by ID.", args = "#spellid" },
    { cat = "Spells", name = "learn", sec = 2, syntax = ".learn #spell [all]", help = "Teach selected player or self a spell.", args = "#spell [all]" },
    { cat = "Spells", name = "unlearn", sec = 2, syntax = ".unlearn #spell [all]", help = "Remove a spell from selected player or self.", args = "#spell [all]" },
    { cat = "Spells", name = "aura", sec = 2, syntax = ".aura #spellid", help = "Apply an aura to selected unit.", args = "#spellid" },
    { cat = "Spells", name = "unaura", sec = 2, syntax = ".unaura #spellid", help = "Remove an aura from selected unit.", args = "#spellid" },
    { cat = "Spells", name = "cooldown", sec = 2, syntax = ".cooldown [#spell_id]", help = "Clear selected spell cooldown or all cooldowns.", args = "[#spell_id]" },
    { cat = "Spells", name = "learn all my spells", sec = 2, syntax = ".learn all my spells", help = "Learn all class spells for your character." },
    { cat = "Spells", name = "learn all my talents", sec = 2, syntax = ".learn all my talents", help = "Learn all talents for your character." },
    { cat = "Spells", name = "learn all gm", sec = 2, syntax = ".learn all gm", help = "Learn default GM spells." },

    { cat = "Character", name = "levelup", sec = 2, syntax = ".levelup [$playername] [#levels]", help = "Increase level for selected/self/player.", args = "[#levels]" },
    { cat = "Character", name = "modify money", sec = 2, syntax = ".modify money #money", help = "Modify selected player's money in copper.", args = "#copper" },
    { cat = "Character", name = "modify speed", sec = 2, syntax = ".modify speed $speedtype #rate", help = "Modify movement speed. Speed types include fly, all, walk, backwalk, and swim.", args = "$speedtype #rate" },
    { cat = "Character", name = "modify scale", sec = 2, syntax = ".modify scale #scale", help = "Modify selected unit scale.", args = "#scale" },
    { cat = "Character", name = "maxskill", sec = 2, syntax = ".maxskill", help = "Set all known skills to maximum." },
    { cat = "Character", name = "setskill", sec = 2, syntax = ".setskill #skill #level [#max]", help = "Set skill level for selected/self.", args = "#skill #level [#max]" },
    { cat = "Character", name = "revive", sec = 2, syntax = ".revive", help = "Revive selected player or self." },
    { cat = "Character", name = "die", sec = 2, syntax = ".die", help = "Kill selected unit." },
    { cat = "Character", name = "save", sec = 0, syntax = ".save", help = "Save your character." },
    { cat = "Character", name = "saveall", sec = 1, syntax = ".saveall", help = "Save all players." },

    { cat = "Teleport", name = "lookup teleport", sec = 1, syntax = ".lookup teleport $substring", help = "Search teleport locations.", args = "$substring" },
    { cat = "Teleport", name = "teleport", sec = 2, syntax = ".teleport #location", help = "Teleport yourself to a named location.", args = "#location" },
    { cat = "Teleport", name = "teleport name", sec = 2, syntax = ".teleport name [#playername] #location", help = "Teleport player to location.", args = "[#playername] #location" },
    { cat = "Teleport", name = "appear", sec = 1, syntax = ".appear [$charactername]", help = "Teleport to a character.", args = "[$charactername]" },
    { cat = "Teleport", name = "summon", sec = 1, syntax = ".summon [$charactername]", help = "Summon character to you.", args = "[$charactername]" },
    { cat = "Teleport", name = "recall", sec = 2, syntax = ".recall [$playername]", help = "Teleport player to previous location.", args = "[$playername]" },
    { cat = "Teleport", name = "go creature id", sec = 1, syntax = ".go creature id $creature_template.entry [#spawn]", help = "Teleport to a creature by entry ID.", args = "#entry [#spawn]" },
    { cat = "Teleport", name = "go creature name", sec = 1, syntax = ".go creature name $creature_template.name", help = "Teleport to a creature by exact name.", args = "$name" },
    { cat = "Teleport", name = "go xyz", sec = 1, syntax = ".go xyz #x #y #z [#mapid] [#orientation]", help = "Teleport to coordinates.", args = "#x #y #z [#mapid]" },

    { cat = "NPCs", name = "lookup creature", sec = 1, syntax = ".lookup creature $namepart", help = "Search creatures by name.", args = "$namepart" },
    { cat = "NPCs", name = "npc add", sec = 2, syntax = ".npc add #creatureid", help = "Spawn creature at your location.", args = "#creatureid" },
    { cat = "NPCs", name = "npc delete", sec = 2, syntax = ".npc delete [#guid]", help = "Delete selected creature or GUID.", args = "[#guid]" },
    { cat = "NPCs", name = "npc info", sec = 1, syntax = ".npc info", help = "Show selected creature information." },
    { cat = "NPCs", name = "npc move", sec = 2, syntax = ".npc move [#guid]", help = "Move selected creature to your location.", args = "[#guid]" },
    { cat = "NPCs", name = "npc set level", sec = 2, syntax = ".npc set level #level", help = "Set selected creature level.", args = "#level" },
    { cat = "NPCs", name = "npc set factionid", sec = 2, syntax = ".npc set factionid #factionid", help = "Set selected creature faction.", args = "#factionid" },
    { cat = "NPCs", name = "npc near", sec = 2, syntax = ".npc near [#distance]", help = "List nearby creatures.", args = "[#distance]" },

    { cat = "Quests", name = "lookup quest", sec = 1, syntax = ".lookup quest $namepart", help = "Search quests by name.", args = "$namepart" },
    { cat = "Quests", name = "quest add", sec = 2, syntax = ".quest add #quest_id", help = "Add quest to selected/self.", args = "#quest_id" },
    { cat = "Quests", name = "quest complete", sec = 2, syntax = ".quest complete #quest_id", help = "Complete quest objectives for selected/self.", args = "#quest_id" },
    { cat = "Quests", name = "quest remove", sec = 2, syntax = ".quest remove #quest_id", help = "Remove quest from selected/self.", args = "#quest_id" },
    { cat = "Quests", name = "quest reward", sec = 2, syntax = ".quest reward #quest_id", help = "Reward quest for selected/self.", args = "#quest_id" },

    { cat = "Server", name = "announce", sec = 2, syntax = ".announce $message", help = "Broadcast a global message.", args = "$message" },
    { cat = "Server", name = "server info", sec = 0, syntax = ".server info", help = "Display server information." },
    { cat = "Server", name = "server motd", sec = 0, syntax = ".server motd", help = "Display message of the day." },
    { cat = "Server", name = "server restart", sec = 3, syntax = ".server restart #delay", help = "Restart worldserver after delay.", args = "#delay" },
    { cat = "Server", name = "server shutdown", sec = 3, syntax = ".server shutdown #delay", help = "Shut down worldserver after delay.", args = "#delay" },
    { cat = "Server", name = "reload config", sec = 3, syntax = ".reload config", help = "Reload server configuration." },
}

GMCC_QUICK_ACTIONS = {
    { label = "GM On", command = ".gm on" },
    { label = "GM Off", command = ".gm off" },
    { label = "Visible On", command = ".gm visible on" },
    { label = "Invisible", command = ".gm visible off" },
    { label = "Fly On", command = ".gm fly on" },
    { label = "Fly Off", command = ".gm fly off" },
    { label = "Revive", command = ".revive" },
    { label = "Cooldowns", command = ".cooldown" },
    { label = "Repair", command = ".gear repair" },
    { label = "Max Skills", command = ".maxskill" },
    { label = "Save Me", command = ".save" },
    { label = "Save All", command = ".saveall" },
}

GMCC_LOOKUPS = {
    { label = "Lookup Item", command = ".lookup item %s", url = "https://wotlkdb.com/?search=%s" },
    { label = "Add Item", command = ".additem %s %s", url = "https://wotlkdb.com/?item=%s" },
    { label = "Lookup Spell", command = ".lookup spell %s", url = "https://wotlkdb.com/?search=%s" },
    { label = "Learn Spell", command = ".learn %s", url = "https://wotlkdb.com/?spell=%s" },
    { label = "Lookup Creature", command = ".lookup creature %s", url = "https://wotlkdb.com/?search=%s" },
    { label = "Go Creature ID", command = ".go creature id %s", url = "https://wotlkdb.com/?npc=%s" },
    { label = "Lookup Quest", command = ".lookup quest %s", url = "https://wotlkdb.com/?search=%s" },
    { label = "Add Quest", command = ".quest add %s", url = "https://wotlkdb.com/?quest=%s" },
    { label = "Lookup Tele", command = ".lookup teleport %s" },
    { label = "Teleport", command = ".teleport %s" },
}
